-- 코드를 입력하세요 식당 ID, 식당 이름, 음식 종류, 즐겨찾기수, 주소, 리뷰 평균 점수
SELECT
    i.REST_ID,
    i.REST_NAME,
    i.FOOD_TYPE,
    i.FAVORITES,
    i.ADDRESS,
    ROUND(AVG(r.REVIEW_SCORE), 2) AS AVG_SCORE
FROM REST_INFO AS i
JOIN REST_REVIEW AS r
ON i.REST_ID = r.REST_ID
WHERE i.ADDRESS LIKE "서울%"
GROUP BY
    i.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.FAVORITES, i.ADDRESS
ORDER BY AVG_SCORE DESC, FAVORITES DESC;
