WITH RECURSIVE tree AS (
    -- 1세대
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    -- 하위 세대로 확장
    SELECT e.ID, e.PARENT_ID, t.GENERATION + 1
    FROM ECOLI_DATA e
    JOIN tree t ON e.PARENT_ID = t.ID
)
SELECT 
    COUNT(*) AS COUNT,
    t.GENERATION AS GENERATION
FROM tree t
LEFT JOIN ECOLI_DATA c
ON c.PARENT_ID = t.ID
WHERE c.ID IS NULL
GROUP BY t.GENERATION
ORDER BY t.GENERATION;

