# SIZE_OF_COLONY가
# 100 보다 작음 LOW
# 100 초과 1000 이하면 MEDIUM
# 1000 초과라면 HIGH

SELECT 
    ID,
    CASE
        WHEN SIZE_OF_COLONY < 100 THEN 'LOW'
        WHEN SIZE_OF_COLONY <= 1000 THEN 'MEDIUM'
        ELSE 'HIGH'
    END AS SIZE
FROM ECOLI_DATA
ORDER BY ID;

    