-- 코드를 입력하세요
SELECT
    fh.FLAVOR
FROM FIRST_HALF AS fh
LEFT JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_TOTAL
    FROM JULY
    GROUP BY FLAVOR
) AS j
ON j.FLAVOR = fh.FLAVOR
ORDER BY (fh.TOTAL_ORDER + IFNULL(j.JULY_TOTAL, 0)) DESC
LIMIT 3;