-- 코드를 작성해주세요
SELECT 
    c.ITEM_ID,
    i.ITEM_NAME,
    i.RARITY
FROM ITEM_TREE c
JOIN ITEM_INFO p ON p.ITEM_ID = c.PARENT_ITEM_ID AND p.RARITY = 'RARE'
JOIN ITEM_INFO i ON i.ITEM_ID = c.ITEM_ID
ORDER BY c.ITEM_ID DESC;


