-- 코드를 작성해주세요
SELECT 
    f.ID,
    n.FISH_NAME,
    f.LENGTH
FROM FISH_INFO f
JOIN (
    SELECT FISH_TYPE,
    MAX(LENGTH) AS MAX_LEN
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) m
ON m.FISH_TYPE = f.FISH_TYPE
AND f.LENGTH = m.MAX_LEN
JOIN FISH_NAME_INFO n
ON n.FISH_TYPE = f.FISH_TYPE
ORDER BY f.ID;